# Generated by Django 4.0.4 on 2022-06-13 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_email', models.CharField(max_length=20, unique=True)),
                ('client_password', models.CharField(max_length=20)),
                ('Client_nickname', models.CharField(max_length=20, unique=True)),
                ('Client_img', models.ImageField(upload_to='')),
                ('intro', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('Review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Review_content', models.TextField(verbose_name=django.core.validators.MinLengthValidator(5, '너무 짧군요!'))),
                ('Review_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
